add_newline = true

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 30
style = "bold red"

[character]
use_symbol_for_status = true
symbol = "  ➟"     # The "symbol" segment is being set to "➜"
# error_symbol = "  ✗"
style_success = "bold #00A652"
style_failure = "bold #df382c"
error_symbol = "[✖](bold red) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = "⌛ "
show_milliseconds = false
disabled = false
style = "bold italic #87A752"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "🍣 "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
progress_divider = " of "

[git_status]
conflicted = "⚔️ "
ahead = "🏎️ 💨 ×${count}"
behind = "🐢 ×${count}"
diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count}"
untracked = "🤷 ×${count}"
stashed = "📦 "
modified = "📝 ×${count}"
staged = "🗃️  ×${count}"
renamed = "📛 ×${count}"
deleted = "🗑️  ×${count}"
style = "bright-white"
format = "$all_status$ahead_behind"

[golang]
symbol = "G "

[hostname]
ssh_only = false
# suffix = ">>"
trim_at = ".companyname.com"
disabled = false
style = "bold italic #87A752"

[line_break]
disabled = true

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
show_percentage = true
show_swap = true
threshold = 70
style = "bold dimmed white"
disabled = false

[python]
symbol = "🐍 "
pyenv_version_name = true
pyenv_prefix = "foo "

[rust]
symbol = "🦀 "
format = "via [🦀 $version](red bold)"

[time]
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = false
